export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_REG = 'AUTH_REG'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const RIGHT_ANSWER = 'RIGHT_ANSWER'
export const WRONG_ANSWER = 'WRONG_ANSWER'
